/**
 * How many third-party components the product ships.
 *
 * The number shown on the About page (and in the runtime information) is not guessed and not hard-coded:
 * it is read from the notice file generated by `npm run licenses`, which lists every library and font
 * family that is bundled into the application. When that file is missing — for example when someone runs
 * the source without generating the notices — the count falls back to the declared runtime dependencies
 * rather than inventing a figure.
 */

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

export interface ThirdPartyCountOptions {
  /** Candidate paths of the notice file, in the order they should be tried. */
  noticeFiles: string[]
  /** Path of a `package.json` whose `dependencies` are the fallback. */
  manifestFile?: string
}

export function countThirdPartyComponents(options: ThirdPartyCountOptions): number {
  for (const file of options.noticeFiles) {
    if (!file || !existsSync(file)) continue
    try {
      const lines = readFileSync(file, 'utf8').split('\n')
      const components = lines.filter((line) => line.startsWith('* ')).length
      if (components > 0) return components
    } catch {
      // unreadable file: try the next candidate
    }
  }
  if (options.manifestFile && existsSync(options.manifestFile)) {
    try {
      const manifest = JSON.parse(readFileSync(options.manifestFile, 'utf8')) as {
        dependencies?: Record<string, string>
      }
      return Object.keys(manifest.dependencies ?? {}).length
    } catch {
      return 0
    }
  }
  return 0
}

/** Notice-file candidates that work both in the packaged application and from the repository. */
export function noticeFileCandidates(resourcesPath: string | null, appPath: string): string[] {
  return [
    resourcesPath ? join(resourcesPath, 'legal', 'THIRD-PARTY-NOTICES.txt') : null,
    join(appPath, 'docs', 'compliance', 'THIRD-PARTY-NOTICES.txt'),
    join(process.cwd(), 'docs', 'compliance', 'THIRD-PARTY-NOTICES.txt')
  ].filter((entry): entry is string => entry !== null)
}

/** The same notice file, resolved from a repository checkout (used by the maintenance tooling). */
export function repositoryNoticeFile(repositoryRoot: string): string {
  return join(repositoryRoot, 'docs', 'compliance', 'THIRD-PARTY-NOTICES.txt')
}
