/**
 * The Dentiva Pro application mark.
 *
 * The image is the branding file generated by `scripts/generate-icons.mjs` (`assets/branding/logo.svg`),
 * which is committed so a fresh checkout builds without running the icon generator first. Vite inlines
 * the SVG into the renderer bundle, so the mark also works in the packaged application with no runtime
 * file lookup.
 */

import logo from '@branding/logo.svg'

export function BrandMark({
  className = 'auth-card__brand-mark',
  size
}: {
  className?: string
  /** Optional square size in pixels; the default follows the class it is given. */
  size?: number
}): React.ReactElement {
  return (
    <span className={className} style={size ? { width: size, height: size } : undefined} aria-hidden="true">
      <img className="brand-mark__image" src={logo} alt="" draggable={false} />
    </span>
  )
}
